OMAKUB_THEME_COLOR="magenta"
DEBIANOK_THEME_COLOR="$OMAKUB_THEME_COLOR"
OMAKUB_THEME_BACKGROUND="catppuccin/background.png"
DEBIANOK_THEME_BACKGROUND="$OMAKUB_THEME_BACKGROUND"
source $OMAKUB_PATH/themes/set-gnome-theme.sh
