OMAKUB_THEME_COLOR="purple"
DEBIANOK_THEME_COLOR="$OMAKUB_THEME_COLOR"
OMAKUB_THEME_BACKGROUND="kanagawa/background.jpg"
DEBIANOK_THEME_BACKGROUND="$OMAKUB_THEME_BACKGROUND"
source $OMAKUB_PATH/themes/set-gnome-theme.sh
