OMAKUB_THEME_COLOR="bark"
DEBIANOK_THEME_COLOR="$OMAKUB_THEME_COLOR"
OMAKUB_THEME_BACKGROUND="everforest/background.jpg"
DEBIANOK_THEME_BACKGROUND="$OMAKUB_THEME_BACKGROUND"
source $DEBIANOK_PATH/themes/set-gnome-theme.sh
